name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Test, Lint, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run type checking
        run: |
          cd apps/web && npx tsc --noEmit
          cd ../mcp && npx tsc --noEmit

      - name: Run linting
        run: |
          cd apps/web && npx next lint
          cd ../mcp && npx eslint src test

      - name: Check formatting
        run: npx prettier --check .

      - name: Run tests
        run: |
          cd apps/web && npx vitest run
          cd ../mcp && npx vitest run
