name: Deploy to Cloudflare

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-mcp:
    name: Deploy MCP Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Upload MCP Secrets
        run: |
          cd apps/mcp
          echo "${{ secrets.OAUTH_CLIENT_ID }}" | npx wrangler secret put OAUTH_CLIENT_ID --name medlock-mcp-server --env="" --no-interaction
          echo "${{ secrets.OAUTH_CLIENT_SECRET }}" | npx wrangler secret put OAUTH_CLIENT_SECRET --name medlock-mcp-server --env="" --no-interaction
          echo "${{ secrets.SOLID_SIGNING_KEY }}" | npx wrangler secret put SOLID_SIGNING_KEY --name medlock-mcp-server --env="" --no-interaction
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy MCP to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/mcp
          command: deploy -c wrangler.production.jsonc
          packageManager: yarn

  deploy-web:
    name: Deploy Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Web App
        run: cd apps/web && yarn build:cloudflare

      - name: Deploy Web to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/web
          command: deploy -c wrangler.production.jsonc
          packageManager: yarn
